<h1> Data Spaces' Tesina <h1>

<p>Imports section<p>

In [1]:
import numpy as np
from sklearn import neighbors, model_selection, metrics, preprocessing
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

<p> Read .csv file <p>

In [2]:
filename = "dataR2.csv"
file = open(filename, "r")

data = np.loadtxt(file, delimiter=",", dtype=None, encoding=None, usecols=(0,1,2,3,4,5,6,7,8,9), skiprows=1)

# according to the relevant papers indicated in the website where I took this dataset from has been has been
# observed that if instead of taking into account all of the features we only take 4 of them (Age, BMI, Glucose
# & Resistine) we can achieve a grater accuracy (only if we are using the SVM or at least Random Forest algos
# whereas with KNN or Logistic regression results aren't that nice).

# data = np.loadtxt(file, delimiter=",", dtype=None, encoding=None, usecols=(0,1,2,7,9), skiprows=1)

# records with the classification as "1" are Healthy Controls, "2" means Patients.

<p>Preprocessing</p>

In [3]:
# Let's divide data into source and target (respectively X and Y)
X = data[:, :-1]
Y = data[:, len(data[0])-1]

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, random_state=np.random.randint(0,100), test_size=0.3)

# array of possible K to apply KNN neighbors
ks = [3,5,7,9]


# normalize data because algorithms work better with normalized data
scaler = preprocessing.StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

<p> I try to apply PCA on the dataset, since there are 10 features (which are a lot) and then re-apply KNN <p>

In [4]:
# pca = PCA(n_components=4)
# pca.fit(X)
# Xp = pca.transform(X)
# print(Xp)

# X_train, X_test, Y_train, Y_test = model_selection.train_test_split(Xp, Y, random_state=np.random.randint(0,100), test_size=0.3)

# # array of possible K to apply KNN neighbors
# ks = [3,5,7,9]


# normalize data because algorithms work better with normalized data
# scaler = preprocessing.StandardScaler()
# scaler.fit(X_train)
# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

[[-1.18146727e+02 -3.37452543e+01 -5.34841916e-02  1.70821312e+00]
 [-6.61259970e+01 -1.03555210e+01 -2.30719162e+01 -2.30978016e+01]
 [ 1.97682203e+01 -7.54628627e+00 -1.35367716e+01 -2.26901307e+01]
 [ 3.93026665e+02 -3.15569321e+01 -6.31341141e+00 -1.71098988e+01]
 [ 2.39018611e+02 -1.50451951e+01 -2.32045340e+01 -2.68809720e+01]
 [-4.48478724e+00 -1.92517387e+01 -1.12542953e+01  8.58458195e+00]
 [ 7.20834300e+02 -3.36783053e+01 -1.40021544e+01 -3.73978966e+01]
 [-2.53712444e+02  1.00634944e+01 -3.66526115e+01 -4.61678191e+00]
 [-3.97876374e+02 -4.80650797e+00 -2.66188674e+01 -8.81612683e+00]
 [-2.16691095e+02 -1.13422142e+01 -9.66513340e+00 -1.86263293e+01]
 [-1.80539609e+02 -2.68350154e+01  4.91473279e+00  1.66816880e+01]
 [-3.60275845e+02 -1.10781786e+01  2.03291198e+01  2.09896512e+01]
 [-2.21387656e+02 -2.24301618e+01  1.05930874e+01  2.61986557e+01]
 [ 9.70825047e+01 -2.96214287e+01  3.54640950e-01  3.12825437e+01]
 [-3.70086154e+02 -2.36998777e+01  5.00109464e+00  1.41112175e

<p>Apply K-NN</p>

In [5]:
for k in ks:
    n_neighbors = k
    
    # Create an instance of neighbors classifier (clf) and fit the data
    clf = neighbors.KNeighborsClassifier(n_neighbors)
    
    # train the classifier on the training set
    clf.fit(X_train, Y_train)
    
    print("Accuracy score on the test set with K =",n_neighbors,"is %.3f" %(clf.score(X_test, Y_test)))


    

Accuracy score on the test set with K = 3 is 0.743
Accuracy score on the test set with K = 5 is 0.686
Accuracy score on the test set with K = 7 is 0.771
Accuracy score on the test set with K = 9 is 0.829


<p>Apply KNN this time with a validation set </p>

In [6]:
# Let's create the validation set
X_train_t, X_valid, Y_train_t, Y_valid = model_selection.train_test_split(X_train, Y_train, random_state=np.random.randint(0,100), test_size=0.30)

# array of possible K to apply KNN neighbors
ks = [3,5,7,9]

# normalize data because algorithms work better with normalized data
scaler = preprocessing.StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_valid = scaler.transform(X_valid)

# array to write accuracy values for each K 
acc_arr = []

for k in ks:
    n_neighbors = k
    
    # Create an instance of neighbors classifier (clf) and fit the data
    clf = neighbors.KNeighborsClassifier(n_neighbors)
    
    # train the classifier on the training set
    clf.fit(X_train_t, Y_train_t)
    
    acc_arr.append(clf.score(X_valid, Y_valid))
    
# I choose the best K based on the results on the validation set and apply KNN with that
k_best_index = acc_arr.index(max(acc_arr))
k_best = ks[k_best_index]

clf2 = neighbors.KNeighborsClassifier(k_best)
clf2.fit(X_train_t, Y_train_t)

print("The best K, based on the validation set results, is",k_best,"and the accuracy on the test set is %.3f"%(clf2.score(X_test, Y_test)))

The best K, based on the validation set results, is 9 and the accuracy on the test set is 0.743


<p> I'll try Logistic Regression on the dataset <p>

In [7]:
logReg = LogisticRegression(solver="lbfgs") # instance of the model

logReg.fit(X_train, Y_train)

# res = logReg.predict(X_test)

print("Accuracy: ", logReg.score(X_test, Y_test))

Accuracy:  0.7714285714285715


<p><u> Naive Bayes classifier </u></p>

In [8]:
gnb = GaussianNB()
gnb.fit(X_train, Y_train)
print("Accuracy: ", gnb.score(X_test, Y_test))

Accuracy:  0.5142857142857142


<p><u> Random forest</u> </p>

In [9]:
rndFor = RandomForestClassifier(n_estimators = 200, criterion="entropy")

rndFor.fit(X_train, Y_train)

y_pred = rndFor.predict(X_test)

print("Accuracy: ", metrics.accuracy_score(Y_test, y_pred))

Accuracy:  0.6285714285714286


<p><u> SVM</u> </p>

In [10]:
svc = SVC(gamma='auto', kernel='rbf')
svc.fit(X_train, Y_train)
print("Accuracy: ", svc.score(X_test, Y_test))

Accuracy:  0.6571428571428571


<p> So this is the accuracy with the default parameters, but with SVm approach is necessary to perform some parameters tuning in order to achieve a better result. To do so I relied on the GridSearch <p>
<p><u> SVM with GridSearch </u></p>

In [11]:
parameters = [{'C': [0.1, 1, 10, 100, 1000], 'gamma': [0.0001, 0.001, 0.01, 0.1, 1], 'kernel': ['rbf']}]
svcGS = GridSearchCV(svc, parameters, n_jobs=-1, cv=3)
svcGS.fit(X_train, Y_train)
print("Accuracy: ", svcGS.score(X_test, Y_test))

Accuracy:  0.8
